<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEV0EfjC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEV0EfjC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEV0EfjC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEV0EfjC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEV0EfjC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'EV0EfjC',
    'container.build_id' => '6f1af077',
    'container.build_time' => 1573997071,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEV0EfjC');
