<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB83CGVD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB83CGVD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB83CGVD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB83CGVD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB83CGVD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B83CGVD',
    'container.build_id' => 'c7fb78a5',
    'container.build_time' => 1573995025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB83CGVD');
