<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8bPxU4k\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8bPxU4k/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8bPxU4k.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8bPxU4k\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8bPxU4k\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8bPxU4k',
    'container.build_id' => '157d87de',
    'container.build_time' => 1573926321,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8bPxU4k');
